
# Starship configuration.

add_newline = true

command_timeout = 1000

format = "$env_var$username$hostname$localip$shlvl$singularity$kubernetes$directory$vcsh$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$docker_context$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$buf$nix_shell$conda$meson$spack$memory_usage$aws$gcloud$openstack$azure$crystal$custom$sudo$cmd_duration$line_break$jobs$battery$time$status$os$container$shell$character"

scan_timeout = 100

[aws]

disabled = true

[aws.region_aliases]

af-south-1 = "AFRICA - Cape Town"
ap-east-1 = "APAC - Hong Kong"
ap-northeast-1 = "APAC - Tokyo"
ap-northeast-2 = "APAC - Seoul"
ap-northeast-3 = "APAC - Osaka"
ap-south-1 = "APAC - Mumbai"
ap-southeast-1 = "APAC - Singapore"
ap-southeast-2 = "APAC - Sydney"
ca-central-1 = "Canada - Central"
cn-north-1 = "CHINA - Beijing"
cn-northwest-1 = "CHINA - Ningxia"
eu-central-1 = "Europe - Frankfurt"
eu-south-1 = "Europe - Milan"
eu-west-1 = "Europe - Ireland"
eu-west-2 = "Europe - London"
eu-west-3 = "Europe - Paris"
me-south-1 = "ME - Bahrain"
sa-east-1 = "AMER - Sao Paulo"
us-east-1 = "AMER - Ohio"
us-east-2 = "AMER - N. Virginia"
us-gov-east-1 = "AMER - GovCloud - US East"
us-gov-west-1 = "AMER - GovCloud - US West"
us-west-1 = "AMER - California"
us-west-2 = "AMER - Oregon"

[azure]

disabled = true

[battery]

charging_symbol = "âš¡"
disabled = false
discharging_symbol = "ğŸª«"
empty_symbol = "ğŸ’€"
full_symbol = "ğŸ”‹"
unknown_symbol = "â“"

[[battery.display]]

style = "bold red"
threshold = 10

[[battery.display]]

style = "bold orange"
threshold = 30

[[battery.display]]

style = "bold yellow"
threshold = 75

[[battery.display]]

style = "bold green"
threshold = 100

[character]

disabled = false
error_symbol = "[X](bold red)"
success_symbol = "[â¯](bold green)"
#vicmd_symbol = "[â®](bold green)"

[cmake]

disabled = false

[cmd_duration]

disabled = false
min_time = 2000
show_milliseconds = false

[container]

disabled = false

[directory]

disabled = false

[docker_context]

disabled = false

[env_var]

[env_var.OS_LAYER]

disabled = false
format = "[$symbol$env_value]($style)\n"
style = "bold orange"
symbol = "ğŸ° "
variable = "OS_LAYER"

[gcloud]

disabled = true

[gcloud.region_aliases]

asia-east1 = "Changhua County, Taiwan"
asia-east2 = "Hong Kong"
asia-northeast1 = "Tokyo, Japan"
asia-northeast2 = "Osaka, Japan"
asia-northeast3 = "Seoul, South Korea"
asia-south1 = "Mumbai, India"
asia-southeast1 = "Jurong West, Singapore"
asia-southeast2 = "Jakarta, Indonesia"
australia-southeast1 = "Sydney, Australia"
europe-north1 = "Hamina, Finland"
europe-west1 = "St. Ghislain, Belgium"
europe-west2 = "London, England, UK"
europe-west3 = "Frankfurt, Germany"
europe-west4 = "Eemshaven, Netherlands"
europe-west6 = "ZÃ¼rich, Switzerland"
northamerica-northeast1 = "MontrÃ©al, QuÃ©bec, Canada"
southamerica-east1 = "Osasco (SÃ£o Paulo), Brazil"
us-central1 = "Council Bluffs, Iowa, USA"
us-east1 = "Moncks Corner, South Carolina, USA"
us-east4 = "Ashburn, Northern Virginia, USA"
us-west1 = "The Dalles, Oregon, USA"
us-west2 = "Los Angeles, California, USA"
us-west3 = "Salt Lake City, Utah, USA"
us-west4 = "Las Vegas, Nevada, USA"

[git_branch]

disabled = false

[git_commit]

disabled = false

[git_metrics]

disabled = false

[git_state]

disabled = false

[git_status]

disabled = false

[golang]

disabled = false

[helm]

disabled = false

[hostname]

disabled = false

[jobs]

disabled = false

[kubernetes]

disabled = false

[line_break]

disabled = false

[memory_usage]

disabled = false
symbol = "ğŸ"

[nix_shell]

disabled = false

[nodejs]

disabled = false

[os]

disabled = false

[os.symbols]

Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
RedHatEnterprise = "ïŒ– "
Redhat = "ïŒ– "
Redox = "ï”— "
SUSE = "ïŒ” "
Solus = "ï´± "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "
openSUSE = "ïŒ” "

[package]

disabled = false

[pulumi]

disabled = false

[python]

disabled = false

[ruby]

disabled = false

[rust]

disabled = false

[shlvl]

disabled = false

[singularity]

disabled = false

[status]

disabled = false

[sudo]

disabled = true

[terraform]

disabled = false

[time]

disabled = false
format = "ğŸ•™ [$time]($style) "

[username]

disabled = false
